# Generated by Django 2.1.4 on 2019-01-03 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aparato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('aparato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Aparato')),
            ],
            options={
                'db_table': 'calificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'competencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('edad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Competencia')),
            ],
            options={
                'db_table': 'competidor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gimnasio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Aparato')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'nivel',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='competidor',
            name='gimnasio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Gimnasio'),
        ),
        migrations.AddField(
            model_name='competidor',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Grupo'),
        ),
        migrations.AddField(
            model_name='competidor',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Nivel'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='competidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Competidor'),
        ),
    ]
