# Generated by Django 2.1.4 on 2019-01-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190104_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='nombre',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
