# Generated by Django 2.1.4 on 2019-02-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_competencia_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': True,
            },
        ),
    ]
