# Generated by Django 2.1.4 on 2019-02-23 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_competidor_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competidor',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='competidor',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='config.Genero'),
        ),
    ]
