# Generated by Django 2.1.4 on 2019-02-23 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20190222_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='competidor',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='config.Nivel'),
        ),
    ]
