# Generated by Django 2.1.4 on 2019-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_competidor_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
