# Generated by Django 2.1.4 on 2019-02-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_grupo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='grupo',
        ),
    ]
